### PR TITLE
Add vsdbg to all order groups; add integration test

### PR DESCRIPTION
**Pull request by thitch97**
## Summary
Per [RFC0005](https://github.com/paketo-buildpacks/rfcs/blob/main/text/dotnet-core/0005-debug-support.md#changes-to-the-dotnet-core-buildpack), this commit adds the `vsdbg` buildpack to each of the order groups in `buildpack.toml` along with an integration test.

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Review by ForestEckhardt — APPROVED** [review]

**Comment by sophiewigmore** [comment]
@thitch97 Frankie mentioned that y'all had chatted about a manual testing strategy they mentioned in the issue. Were you able to try this out?

**Comment by thitch97** [comment]
> @thitch97 Frankie mentioned that y'all had chatted about a manual testing strategy they mentioned in the issue. Were you able to try this out?

Still working through that, it'll end up being a How To guide on `paketo-website`.

**Comment by sophiewigmore** [comment]
@thitch97 @ForestEckhardt is anything else needed here or can we merge it in?

**Comment by ForestEckhardt** [comment]
Other than the merge conflict we are all good

**Review by sophiewigmore — APPROVED** [review]

**Pull request merged**
